sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
before_install:
  - sudo apt-get install rbenv
  - sudo apt-get install cppcheck
  - sudo apt-get install valgrind
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"

script:
  - make
  - make cov "CFLAGS = -a -selection -n 10 -s random -P"
  - make check
  - make valgrind "CFLAGS = -a quick -n 5 -s descending -P"
  - make address "CFLAGS = -a heap -n 5 -s almost -P"
  
